### ISSUE TITLE
Bug: Component crashes since 2.5 update

### ISSUE THREAD

**Issue by KubaniGal** [muxinc/elements#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

macOS

### Description

Hi, ever since mux player react version updated to 2.5 (4 days ago) the component fails, i reverted back to 2.4.1 for now, but i wanted to report this to make sure it handled, this happens both locally and when running github checks.
when i reverted back to 2.4.1 the issue was resolved so it must have been the latest version update
 this is the call stack and error:

mux.cjs.js:1 Uncaught TypeError: ue.default.getLevel is not a function
at ../node_modules/mux-embed/dist/mux.cjs.js (mux.cjs.js:1:17456)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:61:1)
at ../node_modules/@mux/playback-core/dist/index.cjs.js (index.cjs.js:1:1777)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:61:1)
at ../node_modules/@mux/mux-player-react/dist/index.cjs.js (index.cjs.js:1:801)
at options.factory (react refresh:6:1)

Thanks in advance.

### Steps to reproduce

1. delete and reinstall node modules(if needed) with version 2.5
2. run locally and open localhost
3. should see the error 

### Current Behavior

fails to navigate to app

### Expected Behavior

should work as it did in previous versions

### Errors

mux.cjs.js:1 Uncaught TypeError: ue.default.getLevel is not a function
at ../node_modules/mux-embed/dist/mux.cjs.js (mux.cjs.js:1:17456)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:61:1)
at ../node_modules/@mux/playback-core/dist/index.cjs.js (index.cjs.js:1:1777)
at options.factory (react refresh:6:1)
at webpack_require (bootstrap:24:1)
at fn (hot module replacement:61:1)
at ../node_modules/@mux/mux-player-react/dist/index.cjs.js (index.cjs.js:1:801)
at options.factory (react refresh:6:1)

### What version of the package are you using?

2.5

**Comment by cjpillsbury** [comment]
Hey @KubaniGal we may need some more details to be able to help investigate this, since we have many use cases of mux player react and haven't yet run into this problem. Is there any chance you can share a simplified reproduction case, like a github repo, codesandbox, or the like?

**Comment by KubaniGal** [comment]
Hey, thanks for the reply..
i hope this will help, this is how we use the player in our project:

      <MuxPlayer
        data-hook={"mux-player"}
        style={{ height: "100%" }}
        streamType="on-demand"
        playbackId={recordedId}
      />

not sure i have more to provide, this works fine in any version that isnt 2.5, in 2.5 the error shows as i attached above

**Comment by scmilee** [comment]
We are also experiencing this issue when bumping to 2.5.0 from 2.4.x . We are bundling the `mux-react-player` in with our internal components library and when consuming the library from either our main React app or a `create-react-app --template typescript` we get the same type error as above.

Interestingly enough, when we directly import and consume `mux-react-player` in the `create-react-app`, everything works fine. Additionally, everything works fine in both scenarios when rolling back to 2.4.2. I see in the release for 2.5.0 a d.ts file was removed for `mux-embed` and maybe that has something to do with it? 

Not exactly sure what would cause this nested dependency type issue.

**Comment by cjpillsbury** [comment]
@KubaniGal @scmilee If either of you can share a codebase + steps to reproduce (codesandbox, stackblitz, public github repo) for the issue, that would go a long way. We and our customers use Mux Player across many react setups that appear to be working fine, so there's almost definitely some other detail in the setup (react versions, build tools, etc. etc.) that's causing the issue to show up.

**Comment by scmilee** [comment]
Here is the [sandbox](https://codesandbox.io/p/github/scmilee/908-reproduction/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvv67vju00063b6t9seic6gl%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvv67vju00023b6tvm10hqfk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvv67vju00043b6t4iuaf2ir%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvv67vju00053b6twu7gcb73%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvv67vju00023b6tvm10hqfk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvv67vju00013b6t4yk9p5b4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvv67vju00023b6tvm10hqfk%2522%252C%2522activeTabId%2522%253A%2522clvv67vju00013b6t4yk9p5b4%2522%257D%252C%2522clvv67vju00053b6twu7gcb73%2522%253A%257B%2522id%2522%253A%2522clvv67vju00053b6twu7gcb73%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clvv6cb1600i73b6tjor8ax7f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvv6cb1600i73b6tjor8ax7f%2522%257D%252C%2522clvv67vju00043b6t4iuaf2ir%2522%253A%257B%2522id%2522%253A%2522clvv67vju00043b6t4iuaf2ir%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvv67vju00033b6tw8u9ydst%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvv67w7p001fddgj72je1btg%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvv67vju00033b6tw8u9ydst%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), if the runtime error isn't covering the preview page it's in the terminal. And as mentioned before, direct usage of the lib will work, only seems to be an issue when it's bundled a level down. 

[Lib repo]( https://github.com/scmilee/muxinc-issue-nine-zero-eight)
[ts react app repo] (https://github.com/scmilee/908-reproduction)

**Comment by abhisheklalnediya** [comment]
I am also facing this issue.

**Comment by czynskee** [comment]
I ran into the same issue here. I was able to fix it by adding this to my webpack config:
```
const config = {
  resolve: {
    extensions: [".js", ".ts", ".tsx"],
    alias: {
      "@mux/mux-player-react": pathLib.resolve(__dirname, "../node_modules/@mux/mux-player-react/dist/index.mjs"),
      }
   }
}
```

**Comment by czynskee** [comment]
I ran into this issue as well:
```
const config = {
  resolve: {
    alias: {
      "@mux/mux-player-react": pathLib.resolve(__dirname, "../node_modules/@mux/mux-player-react/dist/index.mjs")
     }
  }
}
```
I have multiple sub-packages in my project which is why node_modules is one level up from the webpack config.  Not sure if that's related to the root cause.

**Comment by cjpillsbury** [comment]
Hey there folks! We finally were able to prioritize this and dig into root cause. The short version:
- Root cause was actually due to changes in our data sdk library, `mux-embed`, which have been resolved and released in `mux-embed@5.3.1`
- You should be able to resolve right now by upgrading to the **_current_** latest version of Mux Player (or Mux Player React) and just making sure `mux-embed@5.3.1` is installed (aka make sure any `yarn.lock`, `package-lock.json`, or `npm-shrinkwrap.json` don't unintentionally block installing the latest patch of `mux-embed`).
  - You can confirm the version using `npm ls --all mux-embed` or `yarn list mux-embed`
- Although this is a major version bump, it's basically fully backwards compatible, with the following exceptions
  - We've added basic tooltip support, which is on by default. If you want tooltips disabled, set `no-tooltips` attr or `noTooltips` prop.
  - "under the hood" with our UI, our menus have been completely rearchitected. There's one advanced use case backwards compatibility bug that's on our radar that we will be resolving ASAP: we do not currently have player-specific css vars if you want to hide any menu item controls. There are currently workarounds if you use this advanced feature: just let me know!
- In our next release of Mux Player, `mux-embed@^5.3.1` will be enforced (see PR mentioned here) and the aforementioned menu css var bug will be resolved. This _**should**_ happen sometime next week, if you just wanted to wait.

Let me know if there are any questions/comments/concerns here or if you're still having issues after doing ☝️. Sorry for the delay on us being able to prioritize this one!
